Revert "fs, fscrypt: clear DCACHE_ENCRYPTED_NAME when unaliasing directory"
fixes:

../fs/dcache.c:2723:20: error: redefinition of 'fscrypt_handle_d_move'
static inline void fscrypt_handle_d_move(struct dentry *dentry)
                   ^
../include/linux/fscrypt.h:106:20: note: previous definition is here
static inline void fscrypt_handle_d_move(struct dentry *dentry)
                   ^
1 error generated.

This reverts commit 906242d10b0b9279e5fda9691c13500d5b1fb543.

Change-Id: Ie4f4137282013ed2bef667e99c04d1cc63293b1d