drivers: adsprpc: Remove unused variable me in fastrpc_ioctl_control
Fixes:

../drivers/char/adsprpc.c:4201:23: error: unused variable 'me' [-Werror,-Wunused-variable]
        struct fastrpc_apps *me = &gfa;
                             ^
1 error generated.

Change-Id: I59bc623ff484bf44e9350a57c2f40e7d90b4820e