drivers: qca-wifi-host-cmn: Fix error cause a function declaration is deprecated
clang 15.0 warns:

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:91:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
1 error generated.

Change-Id: I8722f15a707a9e5e6bc0a88479b41b0cc318a124
Signed-off-by: fadlyas07 <mhmmdfdlyas@gmail.com>
[07/05/23: Add ce_services_legacy.]