drivers: touchscreen: xiaomi_touch: Fix error cause a function declaration is deprecated
clang 15.0 warns:

../drivers/input/touchscreen/xiaomi/xiaomi_touch.c:145:37: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct class *get_xiaomi_touch_class()
                                    ^
                                     void
../drivers/input/touchscreen/xiaomi/xiaomi_touch.c:150:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device *get_xiaomi_touch_dev()
                                   ^
                                    void
2 errors generated.

Change-Id: I6981975bd60a42d44bbb3f3d7aec74eed11db352
Signed-off-by: fadlyas07 <mhmmdfdlyas@gmail.com>