techpack: data: Fix error cause a function declaration is deprecated
clang 15.0 warns:

../techpack/data/rmnet/perf/rmnet_perf_opt.c:715:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
rmnet_perf_free_hash_table()
                          ^
                           void
1 error generated.

Change-Id: I2fc22515ff7d751458956bd213b3b26bd8ae3ffe