drivers: random: Remove unused random_read
Fixes:

../drivers/char/random.c:1864:1: error: unused function 'random_read' [-Werror,-Wunused-function]
random_read(struct file *file, char __user *buf, size_t nbytes, loff_t *ppos)
^
1 error generated.

Change-Id: Ibcfc0e5a84e9e8f5135239561f45092b5b23dbdb