scsi: ufs: Fix implicit declaration errors
We have no ufs_spin_* nodes in this tree.

Log:

../drivers/scsi/ufs/ufshcd.c:2527:2: error: implicit declaration of function 'ufs_spin_lock_irqsave' [-Werror,-Wimplicit-function-declaration]
 2527 |         ufs_spin_lock_irqsave(hba->host->host_lock, flags);
      |         ^
../drivers/scsi/ufs/ufshcd.c:2527:2: note: did you mean '_raw_spin_lock_irqsave'?
../include/linux/spinlock_api_smp.h:32:26: note: '_raw_spin_lock_irqsave' declared here
   32 | unsigned long __lockfunc _raw_spin_lock_irqsave(raw_spinlock_t *lock)
      |                          ^
../drivers/scsi/ufs/ufshcd.c:2538:2: error: implicit declaration of function 'ufs_spin_unlock_irqrestore' [-Werror,-Wimplicit-function-declaration]
 2538 |         ufs_spin_unlock_irqrestore(hba->host->host_lock, flags);
      |         ^
2 errors generated.

Fixes: 6d72c1ce ("scsi: ufs: atomic update for clkgating_enable").
Change-Id: I06ab776a38a191c20bcf2bb70708b10c27c9ea71