qcom: early_random: Fix compilation for add_hwgenerator_randomness
commit: 5a5ca9290628b5bee2337b326f62492e921b6270 moves the declaration
of function 'add_hwgenerator_randomness' inside random.h so include random.h
to fix below compilation error.

../drivers/soc/qcom/early_random.c:51:3: error: implicit declaration of function 'add_hwgenerator_randomness' [-Werror,-Wimplicit-function-declaration]
                add_hwgenerator_randomness(random_buffer, bytes_received,
                ^
1 error generated.

Change-Id: I5403febdeee92df4b010dc33bf7ab28e6fa2ff7f
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
Signed-off-by: fadlyas07 <mhmmdfdlyas@gmail.com>
(cherry picked from commit 1b3ae3918ad95af3ad72888d286c1e3be48d0b3a)