techpack: camera: Declare cam_ope_mgr_hw_close_u return type
GCC warns:

../techpack/camera/drivers/cam_ope/ope_hw_mgr/cam_ope_hw_mgr.c: At top level:
../techpack/camera/drivers/cam_ope/ope_hw_mgr/cam_ope_hw_mgr.c:3526:8: error: return type defaults to ‘int’ [-Werror=return-type]
 3526 | static cam_ope_mgr_hw_close_u(void *hw_priv, void *hw_close_args)
      |        ^~~~~~~~~~~~~~~~~~~~~~

Change-Id: If84540c49200d271982d1353096fb583acdb4c31
Signed-off-by: fadlyas07 <mhmmdfdlyas@gmail.com>
(cherry picked from commit c61ac8aeb7efe7f21aa19ab87e45f4bb6ff80f2e)